package py.gov.asuncion.demopf.modelo.negocio;
// Generated 18/11/2016 11:08:05 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol implements java.io.Serializable {

    private int id;
    private String descripcion;
    private Set usuarios = new HashSet(0);

    public Rol() {
    }

    public Rol(int id, String descripcion) {
        this.id = id;
        this.descripcion = descripcion;
    }

    public Rol(int id, String descripcion, Set usuarios) {
        this.id = id;
        this.descripcion = descripcion;
        this.usuarios = usuarios;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Set getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

}
